CREATE TABLE IF NOT EXISTS imm_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id TEXT NOT NULL,
    sensor_id TEXT NOT NULL,
    metric TEXT NOT NULL,
    sensor_value TEXT NOT NULL,
    sensor_val_f DOUBLE PRECISION,
    value_dt TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    sensor_status TEXT
);

CREATE INDEX idx_machine_timestamp ON imm_data (machine_id, value_dt);
